#!/usr/bin/env bash

set -euo pipefail
THISDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

function help(){
cat << EOF
police-stats-tools

help        : Display help text
restore     : Fetch dependencies
dev         : Spawn a notebook server
lint        : Lint codebase
unit        : Run unit tests
integration : Run integration tests
EOF
}

function run_restore(){
	uv sync
}

function run_dev(){
	uv run jupyter lab
}

function run_lint(){
	uv run mypy "$THISDIR"/police_stats_tools/
	uv run pylint "$THISDIR"/police_stats_tools/
}

function run_unit(){
	uv run pytest
}

function main(){
	cmd=${1-default}
	shift || true
	case "$cmd" in
		help)
			help "$@"
			;;
		restore)
			run_restore
			;;
		dev)
			run_dev
			;;
		lint)
			run_lint
			;;
		unit)
			run_unit
			;;
		*)
			echo "no-op $cmd"
			;;
	esac
}

main "$@"
